### ISSUE TITLE
Error in import DBSCAN

### ISSUE THREAD

**Issue by Mariana-plr** [VarIr/copac#12]
#### Description
Error in: from sklearn.cluster import DBSCAN when running: from copac import COPAC

#### Files
copac.py

#### To Reproduce
from copac import COPAC

#### Tasks
- line 19:  ".dbscan_" should be removed from: sklearn.cluster.dbscan_ import dbscan.

**Comment by VarIr** [comment]
Apparently the module is called `_dbscan` since sklearn=0.22 or so. You could either
- install sklearn==0.21 or
- locally modify `copac.py` and change "from sklearn.cluster.dbscan_ import dbscan" to "from sklearn.cluster._dbscan import dbscan"

**Comment by VarIr** [comment]
I changed this in copac.py here. Please test, if it works.

**Comment by Mariana-plr** [comment]
Hello, I modified it to "from sklearn.cluster import dbscan" in my local copy and it worked. dbscan is duplicated.
