### ISSUE TITLE
Name and Type errors with DBSCAN

### ISSUE THREAD

**Issue by Mariana-plr** [VarIr/copac#13]
#### Description
Name and Type errors related to dbscan when running copac.fit_predict

#### Screenshots
![image](https://github.com/VarIr/copac/assets/79210610/033d6009-af4f-4b23-981f-7ae5b288e85d)
![image](https://github.com/VarIr/copac/assets/79210610/12189681-ea42-40d2-8ae9-cabc42d4c5fd)
![image](https://github.com/VarIr/copac/assets/79210610/7f4fe5e0-e793-4a54-b420-93d3e805c6e4)

#### Files
copac.py

#### Tasks
The following modifications to lines 168-170 solved the errors.

![image](https://github.com/VarIr/copac/assets/79210610/e4160349-45c6-4cf2-b740-a3c47356618e)

**Comment by VarIr** [comment]
PR welcome :)
