### ISSUE TITLE
Deprecated aliases in numpy

### ISSUE THREAD

**Issue by Mariana-plr** [VarIr/copac#14]
#### Description
AttributeError: module 'numpy' has no attribute 'float' 'int'

#### Screenshots
![image](https://github.com/VarIr/copac/assets/79210610/26eef42a-2538-400c-87b3-bf8f0b16bcc8)
![image](https://github.com/VarIr/copac/assets/79210610/a2de302a-a3b9-4e16-9472-3d0f0f4902fc)

#### Files
copac.py

#### Tasks

- [ ] lines 143, 144: use 'float' and 'int' without 'np.'

**Comment by VarIr** [comment]
Numpy looked quite different 6 years ago. I'd be happy to merge a pull request for this.
